from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class ArtifactDefinition:
    """Describes an artifact generated by the domain framework."""

    artifact_type: str

    name: str

    target_path: str

    template: str = ""