from __future__ import annotations

from dataclasses import dataclass, field

from familyos_cli.domain.generation.artifact_kind import (
    ArtifactKind,
)


@dataclass(frozen=True, slots=True)
class ArtifactDefinition:
    """Describes an artifact generated by the domain framework."""

    kind: ArtifactKind

    name: str

    target_path: str

    template: str

    context: dict[str, object] = field(
        default_factory=dict,
    )
